/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SPI1.h
**     Project     : nrf24l01_qe128
**     Processor   : MC9S08QE128CLK
**     Component   : Init_SPI
**     Version     : Component 01.114, Driver 01.21, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2018-06-17, 19:50, # CodeGen: 3
**     Abstract    :
**          This file implements the SPI (SPI1) module initialization
**          according to the Peripheral Initialization Component settings, and defines
**          interrupt service routines prototypes.
**          The SPI module is the serial peripheral interface module,which allows 
**          full-duplex, synchronous, serial communications with peripheral devices.


**     Settings    :
**          Component name                                 : SPI1
**          Device                                         : SPI1
**          Settings
**            Clock settings
**              Value of Preselection                      : 1
**              Value of Selection                         : 2
**              Frequency                                  : 2097.152 kHz
**            Mode Select                                  : Slave
**            Clock Polarity                               : active-high
**            Clock Phase                                  : Second edge
**            Data shift order                             : MSB first
**            Bidirectional mode                           : Disabled
**            Output enable in Bidirect.                   : no
**            Stop in Wait Mode                            : Disabled
**          Pins
**            SCK pin                                      : PTB2_KBI1P6_SPSCK1_ADP6
**            SCK pin signal                               : 
**            MISO pin allocation                          : Enabled
**            MISO pin                                     : PTB4_TPM2CH1_MISO1
**            MISO pin signal                              : 
**            MOSI pin allocation                          : Enabled
**            MOSI pin                                     : PTB3_KBI1P7_MOSI1_ADP7
**            MOSI pin signal                              : 
**            SS pin allocation                            : Enabled
**            SS pin mode                                  : General Purpose I/O
**            SS pin                                       : PTB5_TPM1CH1_SS1
**            SS pin signal                                : 
**          Interrupts
**            Interrupt                                    : Vspi1
**            Receive and fault interrupt                  : Enabled
**            Transmit Interrupt                           : Enabled
**            ISR name                                     : isrVspi
**          Initialization
**            Call Init in CPU init. code                  : yes
**            Enable SPI system                            : yes
**     Contents    :
**         Init - void SPI1_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SPI1.h
** @version 01.21
** @brief
**          This file implements the SPI (SPI1) module initialization
**          according to the Peripheral Initialization Component settings, and defines
**          interrupt service routines prototypes.
**          The SPI module is the serial peripheral interface module,which allows 
**          full-duplex, synchronous, serial communications with peripheral devices.


*/         
/*!
**  @addtogroup SPI1_module SPI1 module documentation
**  @{
*/         

#ifndef __SPI1
#define __SPI1

/* MODULE SPI1. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"
#include "RF.h"
#include "SPI_func.h"



/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see SPI1.c file for more information).
** ===================================================================
*/
__interrupt void isrVspi(void);
void SPI1_Init(void);
/*
** ===================================================================
**     Method      :  SPI1_Init (component Init_SPI)
**     Description :
**         This method initializes registers of the SPI module
**         according to this Peripheral Initialization Component settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the component for more details. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END SPI1. */
#endif /* ifndef __SPI1 */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
