/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SPI1.c
**     Project     : nrf24l01_qe128
**     Processor   : MC9S08QE128CLK
**     Component   : Init_SPI
**     Version     : Component 01.114, Driver 01.21, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2018-06-17, 19:50, # CodeGen: 3
**     Abstract    :
**          This file implements the SPI (SPI1) module initialization
**          according to the Peripheral Initialization Component settings, and defines
**          interrupt service routines prototypes.
**          The SPI module is the serial peripheral interface module,which allows 
**          full-duplex, synchronous, serial communications with peripheral devices.


**     Settings    :
**          Component name                                 : SPI1
**          Device                                         : SPI1
**          Settings
**            Clock settings
**              Value of Preselection                      : 1
**              Value of Selection                         : 2
**              Frequency                                  : 2097.152 kHz
**            Mode Select                                  : Slave
**            Clock Polarity                               : active-high
**            Clock Phase                                  : Second edge
**            Data shift order                             : MSB first
**            Bidirectional mode                           : Disabled
**            Output enable in Bidirect.                   : no
**            Stop in Wait Mode                            : Disabled
**          Pins
**            SCK pin                                      : PTB2_KBI1P6_SPSCK1_ADP6
**            SCK pin signal                               : 
**            MISO pin allocation                          : Enabled
**            MISO pin                                     : PTB4_TPM2CH1_MISO1
**            MISO pin signal                              : 
**            MOSI pin allocation                          : Enabled
**            MOSI pin                                     : PTB3_KBI1P7_MOSI1_ADP7
**            MOSI pin signal                              : 
**            SS pin allocation                            : Enabled
**            SS pin mode                                  : General Purpose I/O
**            SS pin                                       : PTB5_TPM1CH1_SS1
**            SS pin signal                                : 
**          Interrupts
**            Interrupt                                    : Vspi1
**            Receive and fault interrupt                  : Enabled
**            Transmit Interrupt                           : Enabled
**            ISR name                                     : isrVspi
**          Initialization
**            Call Init in CPU init. code                  : yes
**            Enable SPI system                            : yes
**     Contents    :
**         Init - void SPI1_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SPI1.c
** @version 01.21
** @brief
**          This file implements the SPI (SPI1) module initialization
**          according to the Peripheral Initialization Component settings, and defines
**          interrupt service routines prototypes.
**          The SPI module is the serial peripheral interface module,which allows 
**          full-duplex, synchronous, serial communications with peripheral devices.


*/         
/*!
**  @addtogroup SPI1_module SPI1 module documentation
**  @{
*/         
/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      main.c
**      Events.c
**
** ###################################################################
** */
#include "RF.h"
#include "SPI1.h"

extern T_Buffer transmite;
extern T_Buffer receive;
extern unsigned char Status_check;

__interrupt void isrVspi(void)
{
	/*
	 * ==============================================================
	 * 		Description:
	 * 		Transmission et réception des données du port SPI
	 */
	unsigned char read = 0;
	//(void)getReg8(SPIS);
	if(SPI1S_SPRF == 1){
		read = SPI1D;
		if((receive.p) == &(receive.buffer[SizeBuffer]) || receive.n == 0){
				receive.p = &(receive.buffer[0]);
				receive.n = 0x00;
				SS = 1; /* Passe le Chip select à l'état haut. Arrête le transfert de donnée */
				//Status_check = 0x00; /* On ignore les paquets Status Register envoyés automatiquement */
				Sort_Bytes(&transmite); /* La trame complète est reçu. On trie les informations reçues */
		}
		switch(Status_check){
			case 0x00:
				/* On ignore l'octet récupéré */
				break;
			case 0x01: /* Récupère les informations  */
				if ((read & 0x40) != 0x40){
					transmite.buffer[0] = R_RX_PAYLOAD;
					if((read & 0x0E) != 0x0E)/* Vérifie si la Fixo est pleine */
						receive.n = (read & 0x0E)>>1;	// On retient le nombre d'octet à recevoir
					receive.p = &receive.buffer[0];
					SS = 0;
					SPI_Send(&transmite,1);
					Status_check = 0x02; /* On récupère les prochains octets*/
				}
			case 0x02: /* Reçoit les données de la Fifo Rx */
			default:
				*receive.p = read;
				receive.p++;
				receive.n--;/* Passe à l'octet suivant */
				if(receive.n == 0)
					Status_check = 0x00; /* On ignore les paquets Status Register envoyés automatiquement */
				break;
		}
	}
	/* Transmission de l'octet suivant du buffer */
	if(SPI1S_SPTEF == 1){
		(void)getReg8(SPI1S);
		if(transmite.n == 0){
			SPI1C1_SPTIE = 0;
			clear_buffer(&transmite);
			SS = 1;
			CE = 1;
			return;
		}
		if((transmite.p) >= &(transmite.buffer[SizeBuffer-1]) || transmite.n == 1){
			SPI1C1_SPTIE = 0;
			(void)getReg8(SPI1S);	
			transmite.n = transmite.n--;
			clear_buffer(&transmite);
			CE = 1;
			SS = 1;
			return;
		}
		if ((transmite.p) != &(transmite.buffer[SizeBuffer]) && transmite.n > 0){
			SPI1D = *transmite.p;
			transmite.p++;
			transmite.n = (transmite.n)-1;
		}
	}
}

/* MODULE SPI1. */



/*
** ===================================================================
**     Method      :  SPI1_Init (component Init_SPI)
**     Description :
**         This method initializes registers of the SPI module
**         according to this Peripheral Initialization Component settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the component for more details. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void SPI1_Init(void)
{
  /* SPI1C1: SPIE=0,SPE=0,SPTIE=0,MSTR=0,CPOL=0,CPHA=0,SSOE=0,LSBFE=0 */
  setReg8(SPI1C1, 0x00U);              /* The SPRF interrupt flag is cleared when the SPI1 module is disabled. */ 
  /* SPI1C2: ??=0,??=0,??=0,MODFEN=0,BIDIROE=0,??=0,SPISWAI=0,SPC0=0 */
  setReg8(SPI1C2, 0x00U);               
  /* SPI1BR: ??=0,SPPR2=0,SPPR1=0,SPPR0=0,??=0,SPR2=0,SPR1=0,SPR0=0 */
  setReg8(SPI1BR, 0x00U);               
  (void)getReg8(SPI1S);                /* Dummy read of the SPI1S registr to clear the MODF flag */
  /* SPI1C1: SPIE=1,SPE=1,SPTIE=1,MSTR=0,CPOL=0,CPHA=1,SSOE=0,LSBFE=0 */
  setReg8(SPI1C1, 0xE4U);               
}

/* END SPI1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
